name: tik_tik_clone_all_fetures
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.1"

dependencies:
  cached_network_image: ^3.2.0
  clipboard: ^0.1.3
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^1.1.1
  emoji_picker_flutter: ^1.2.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.17
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.2
  flutter_svg_provider: ^1.0.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  grouped_list: ^5.0.1
  image_picker: ^0.8.5
  modal_bottom_sheet: ^2.0.1
  readmore: ^2.1.0
  timeago: ^3.2.2
  uuid: ^3.0.6
  video_compress: ^3.1.0
  video_player: ^2.4.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: Heebo
  #     fonts:
  #       - asset: assets/fonts/Heebo-VariableFont_wght.ttf
