// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRkRcmfNlX_b-GnwznuwE15kd2_b2fcg',
    appId: '1:1011955249940:web:14ab2de1dac99945f14801',
    messagingSenderId: '1011955249940',
    projectId: 'tiktik-clone-bd54c',
    authDomain: 'tiktik-clone-bd54c.firebaseapp.com',
    storageBucket: 'tiktik-clone-bd54c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxrkRyyDFm1ByYUVyS4bKVpnQYsW4QhHA',
    appId: '1:1011955249940:android:d74ae3ec862e6f18f14801',
    messagingSenderId: '1011955249940',
    projectId: 'tiktik-clone-bd54c',
    storageBucket: 'tiktik-clone-bd54c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2_zs4vEAdTPecb-4uz6i5WuvxqNQdI0',
    appId: '1:1011955249940:ios:167ef9792939c874f14801',
    messagingSenderId: '1011955249940',
    projectId: 'tiktik-clone-bd54c',
    storageBucket: 'tiktik-clone-bd54c.appspot.com',
    androidClientId:
        '1011955249940-fb9kf0nech8erlboq6u8874h43tff9ci.apps.googleusercontent.com',
    iosClientId:
        '1011955249940-v1605bfk687cmdhhg6co6dcn1f4m4ucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikTikCloneAllFetures',
  );
}
